#!/bin/bash

# Define the rota data directly in the script
rota="
03/05/23 name: empty Tee Micro
04/05/23 name: empty Abc Bey
05/05/23 name: empty Test Yest

"

# Get the current date
current_date=$(date +"%d/%m/%y")

# Parse the name of the user on call from the rota data
on_call=$(awk -v today="$current_date" '$1 == today && $2 == "name:" {sub(/name: /, ""); print substr($0, index($0,$3))}' <<< "$rota")

if [[ -n $on_call && $on_call != "empty" ]]; then
    # Display the on-call user on the screen
    osascript -e "display dialog \"$on_call, you are on call this week.\" buttons {\"OK\"} default button 1 with title \"On Call\""
else
    osascript -e "display dialog \"No on-call user found for today.\" buttons {\"OK\"} default button 1 with title \"On Call\""
fi
